version: '3'

services:
  serve:
    build: .
    volumes:
      - ./src:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    environment:
      APP_NAME: 'helloservlet'
      APP_CLASS: 'mypkg'
    command: [ "run.sh" ]
